In [112]:
import pandas as pd

# Import csv data
df = pd.read_csv("songs_normalize.csv")
artist, song, explicit, year, popularity, dance, energy, key, loud, mode, speech, acous, instrumental, live, valence, tempo, genre = df['artist'], df['song'],df['explicit'],df['year'], df['popularity'], df['danceability'], df['energy'], df['key'], df['loudness'], df['mode'],df['speechiness'], df['acousticness'], df['instrumentalness'], df['liveness'],df['valence'],df['tempo'], df['genre']


In [125]:
from sklearn.linear_model import LinearRegression
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_absolute_error
from sklearn.metrics import precision_recall_curve, roc_curve
import matplotlib.pyplot as plt
import numpy as np
from sklearn import metrics
# Choose features
X = df[['danceability', 'energy', 'loudness', 'speechiness','valence', 'tempo']]

# number of datasets 
m = 2000
y_gt = df['genre']

y = np.arange(2000)

# categorize each j
for i in range(m):
    if 'hip hop' in y_gt.iloc[i]:
        y[i] = 1
    elif 'pop' in y_gt.iloc[i]:
        y[i] = 2
    elif 'rock' in y_gt.iloc[i]:
        y[i] = 3
    elif 'R&B' in y_gt.iloc[i]:
        y[i] = 4
    elif 'metal' in y_gt.iloc[i]:
        y[i] = 5
    else:
        y[i] = 0
    

# Set Training datas
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.25)

#logreg = LogisticRegression().fit(X_train, y_train)
logreg = LogisticRegression(multi_class = 'ovr', solver = 'liblinear').fit(X_train, y_train)

In [126]:
prediction = logreg.predict(X_test)
logreg.score(X_test, y_test)
print(metrics.classification_report(y_test, logreg.predict(X_test)))

              precision    recall  f1-score   support

           0       0.00      0.00      0.00        30
           1       0.67      0.56      0.61       178
           2       0.61      0.84      0.71       257
           3       0.00      0.00      0.00        31
           4       0.00      0.00      0.00         3
           5       0.00      0.00      0.00         1

    accuracy                           0.63       500
   macro avg       0.21      0.23      0.22       500
weighted avg       0.55      0.63      0.58       500



C:\Users\13477\anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1245: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\Users\13477\anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1245: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\Users\13477\anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1245: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


In [127]:
m_test = len(prediction)
count = 0
for i in range(len(prediction)):
    if y_test[i] == prediction[i]:
        count += 1
print(count/m_test)
y_score = logreg.predict_proba(X_test)
print(y_score)

0.628
[[0.04619551 0.29784258 0.59327933 0.05399114 0.00474359 0.00394785]
 [0.0368217  0.62772478 0.29456266 0.02243313 0.01215944 0.0062983 ]
 [0.03453267 0.61387316 0.33392008 0.01157945 0.00394477 0.00214987]
 ...
 [0.04110593 0.40484961 0.48044303 0.06368677 0.00522585 0.00468881]
 [0.04357633 0.42376119 0.44527891 0.07545989 0.00505106 0.00687263]
 [0.04512341 0.40517833 0.51129957 0.03024984 0.00487155 0.00327731]]


In [130]:
precision = dict()
recall = dict()
for i in range(6):
    precision[i], recall[i], _ = precision_recall_curve(y_test,
                                                        y_score)
    plt.plot(recall[i], precision[i], lw= 2, label = 'class {}'.format(i))
plt.xlabel("recall")
plt.ylabel("precision")
plt.legend(loc="best")
plt.title("precision vs. recall curve")
plt.show()

ValueError: multiclass format is not supported